# LOCAL VARIABLES ARE WRITE IN function
# AND global VARIABLE ARE WRITE IN OUT OF function

# GLOBAL VARIABLE IS ALWAYS PRINT IF YOU GIVE 2 VARIABLES AND TRY TO PRINT IT BECAUSE 
# global VARIABLE IS HIGH IN VALUE AS COMPARE TO LOCAL AND LOCAL VARIABLE IS VIPE OUT 
# OUT THE function CALLED


def local_global(n):
    n = 1

n = 8
print(n)    

